[package]
name = "tor-hscrypto"
version = "0.1.2"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.60"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Basic onion service cryptography types used by Aerti"
keywords = ["tor", "arti", "cryptography"]
categories = ["cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []

[dependencies]
data-encoding = "2.3.1" # want MSVC i686 build fix, data-encoding/issues/33
derive_more = "0.99.3"
digest = "0.10.0"
itertools = "0.10.1"
paste = "1"
rand_core = "0.6.2"
safelog = { path = "../safelog", version = "0.2.2" }
serde = { version = "1.0.103", features = ["derive"] }
signature = "1"
thiserror = "1"
tor-basic-utils = { path = "../tor-basic-utils", version = "0.6.0" }
tor-bytes = { version = "0.6.3", path = "../tor-bytes" }
tor-llcrypto = { version = "0.4.3", path = "../tor-llcrypto", features = [
    "hsv3-client",
    "hsv3-service",
] }
tor-units = { path = "../tor-units", version = "0.5.0" }

[dev-dependencies]
hex = "0.4"
hex-literal = "0.3"
humantime = "2"
tor-basic-utils = { version = "0.6.0", path = "../tor-basic-utils" }
