[package]
name = "tor-rtmock"
version = "0.8.2"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Testing mock support for tor-rtcomapt"
keywords = ["tor", "arti", "async", "testing"]
categories = ["asynchronous"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
async-trait = "0.1.54"
futures = "0.3.14"
humantime = "2"
pin-project = "1"
thiserror = "1"
tor-rtcompat = { version = "0.9.1", path = "../tor-rtcompat" }
tracing = "0.1.36"

[dev-dependencies]
futures-await-test = "0.3.0"
rand = "0.8"
tor-basic-utils = { path = "../tor-basic-utils", version = "0.7.1" }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.9.1", features = ["tokio", "native-tls"] }

[features]
full = ["tor-rtcompat/full"]
[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
