[package]
name = "tor-config"
version = "0.3.0"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.56"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Low-level configuration for the Arti Tor implementation"
keywords = ["tor", "arti"]
categories = ["config"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = ["expand-paths"]
expand-paths = ["shellexpand", "directories"]

[dependencies]
tor-error = { path = "../tor-error", version = "0.3.0"}
tor-basic-utils = { path="../tor-basic-utils", version = "0.3.0"}

thiserror = "1"
derive_builder = { version = "0.11.2", package = "derive_builder_fork_arti" }
educe = "0.4.6"
once_cell = "1"
paste = "1"
serde = { version = "1.0.103", features = ["derive"] }
shellexpand = { version = "2.1", package = "shellexpand-fork", optional = true }
tracing = "0.1.18"
directories = { version = "4", optional = true }

[dev-dependencies]
config = { version = "0.13", default-features = false, features = ["toml"] }
dirs = "4.0.0"
rmp-serde = "1"
serde_json = "1.0.50"
toml = "0.5"
tracing-test = "0.2"
