[package]
name = "tor-geoip"
version = "0.1.0"
authors = ["The Tor Project, Inc.", "eta <eta@torproject.org>"]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "A crate to parse C Tor GeoIP CSV files."
keywords = ["tor", "arti"]
readme = "README.md"
categories = ["parser-implementations", "network-programming"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[dependencies]
derive_more = "0.99.3"
once_cell = "1.18"
rangemap = "1.3"
thiserror = "1"
tor-error = { path = "../tor-error", version = "0.5.2" }

[features]
embedded-db = []
default = ["embedded-db"]
full = ["tor-error/full", "embedded-db"]
