[package]
name = "tor-ptmgr"
version = "0.2.3"
authors = ["The Tor Project, Inc.", "Nick Mathewson <nickm@torproject.org>"]
edition = "2021"
rust-version = "1.60"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Manage a set of pluggable transports to circumvent censorship"
keywords = ["tor", "arti", "censorship"]
categories = ["network-programming", "cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = ["tor-channel-factory"]
tor-channel-factory = []
full = ["tor-channel-factory"]

experimental = ["experimental-api"]
experimental-api = ["visibility"]

[dependencies]
async-trait = "0.1.2"
derive_builder = { version = "0.11.2", package = "derive_builder_fork_arti" }
fs-mistrust = { version = "0.6.2", path = "../fs-mistrust" }
futures = "0.3.14"
serde = { version = "1.0.103", features = ["derive"] }
thiserror = "1"
tor-chanmgr = { version = "0.8.3", path = "../tor-chanmgr", features = ["pt-client"] }
tor-config = { version = "0.8.0", path = "../tor-config" }
tor-error = { version = "0.4.1", path = "../tor-error" }
tor-linkspec = { version = "0.6.3", path = "../tor-linkspec", features = ["pt-client"] }
tor-rtcompat = { version = "0.8.1", path = "../tor-rtcompat" }
tor-socksproto = { version = "0.6.3", path = "../tor-socksproto" }
tracing = "0.1.18"
visibility = { version = "0.0.1", optional = true }

[dev-dependencies]
anyhow = "1.0.23"
tokio = { version = "1.7", features = [
    "rt",
    "rt-multi-thread",
    "io-util",
    "net",
    "time",
    "macros",
] }
tor-rtcompat = { path = "../tor-rtcompat", version = "0.8.1", features = ["tokio", "native-tls"] }
tracing-subscriber = "0.3.0"

[[example]]
name = "run-pt"
required-features = ["experimental-api"]
