[package]
name = "tor-keymgr"
version = "0.1.0"
authors = ["The Tor Project, Inc.", "Gabriela Moldovan <gabi@torproject.org>"]
edition = "2021"
rust-version = "1.65"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Key management for the Arti Tor implementation"
keywords = ["tor", "arti"]
categories = ["cryptography"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
# Enable experimental APIs that are not yet officially supported.
#
# These APIs are not covered by semantic versioning.  Using this
# feature voids your "semver warrantee".

keymgr = ["__is_experimental", "tor-error/experimental"]
__is_experimental = []
full = ["fs-mistrust/full", "tor-error/full", "tor-hscrypto/full", "tor-llcrypto/full"]
experimental = ["keymgr"]

[dependencies]
derive_more = "0.99.3"
dyn-clone = "1.0.11"
fs-mistrust = { path = "../fs-mistrust", version = "0.7.1", features = ["serde", "walkdir"] }
itertools = "0.10.1"
ssh-key = { version = "0.5.1", features = ["std"] }
thiserror = "1"
tor-error = { path = "../tor-error", version = "0.5.2" }
tor-hscrypto = { path = "../tor-hscrypto", version = "0.3.0" }
tor-llcrypto = { path = "../tor-llcrypto", version = "0.5.2", features = ["keymgr"] }
zeroize = "1"

[dev-dependencies]
tempfile = "3"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
